### ISSUE TITLE
Duplicates ui8_pedal_torque_per_10_bit_ADC_step_x100_array[TORQUE_STEP_DEFAULT] 

### ISSUE THREAD

**Issue by dzid26** [emmebrusa/TSDZ2-Smart-EBike-1#108]
Line `ui8_pedal_torque_per_10_bit_ADC_step_x100_array[TORQUE_STEP_DEFAULT] = PEDAL_TORQUE_PER_10_BIT_ADC_STEP_X100` appears 3 times. It would be good to modify this so that there is no duplication and the intention is clear.

https://github.com/emmebrusa/TSDZ2-Smart-EBike-1/blob/ad782fd3b5691bbf9400e01387ef65ae0ceded79/src/ebike_app.c#L305-L313

**Comment by emmebrusa** [comment]
I saw the report but then forgot about it.
It's a bug. Fixed.

There was also a problem with the power limits, fixed that too.
