### ISSUE TITLE
TSDZ8 Compatibility? 

### ISSUE THREAD

**Issue by UteAkaKute** [emmebrusa/TSDZ2-Smart-EBike-1#117]
I am planning on buying a TSDZ8 from our friends at PSWPower. 
I have looked at a fair bit of forums, but I couldn't find 
people who have tried this OSF on them. Maybe someone here knows something, or could point me in the right direction. 

Or just tells me it's not going to work. In which case I'll have to do with a TSDZ2B (stock firmware obviously is not a choice)

Thanks!

**Comment by dzid26** [comment]
Already discussed https://github.com/emmebrusa/TSDZ2-Smart-EBike-1/issues?q=is%3Aissue++TSDZ8+

**Comment by UteAkaKute** [comment]
Must have overlooked it, sorry. My bad. 
Thanks anyway :)
