### ISSUE TITLE
Cadence Mode

### ISSUE THREAD

**Issue by shimrod673** [emmebrusa/TSDZ2-Smart-EBike-1#17]
Not really an issue with the software so apologies for that.
The torque sensor on my motor has failed so I have changed to cadence mode. It is  working fine but am wondering if the torque sensor is used in the background for any reason and there is a possibility of further damage to the system,

thanks

**Comment by emmebrusa** [comment]
If the motor runs in cadence mode, the torque sensor, even if it is faulty, does not cause any other problems.
