### ISSUE TITLE
Duplicate files and "controller/controller" folder from last commit

### ISSUE THREAD

**Issue by apolselli** [emmebrusa/TSDZ2-Smart-EBike-1#25]
Hello,
some duplicate files ended up by chance into the "master" branch, in a "controller" sub-folder of the "controller" folder:
https://github.com/emmebrusa/TSDZ2-Smart-EBike-1/tree/master/src/controller/controller
I think they should be only in:
https://github.com/emmebrusa/TSDZ2-Smart-EBike-1/tree/master/src/controller

Thank you,
Alessandro.

**Comment by emmebrusa** [comment]
Thanks for the report.
It has been happening ever since I have been using the touchpad instead of the mouse.
