### ISSUE TITLE
Battery %SOC on TSDZ2B with VLCD6 display

### ISSUE THREAD

**Issue by pickerdave** [emmebrusa/TSDZ2-Smart-EBike-1#57]
Hi - my first comment, please be gentle!!! :)
I have a TSDZ2B 36V 350W with VLCD6 display. My configuration is as the attached.
![image](https://user-images.githubusercontent.com/127301018/223685114-bbb6cc97-fbf7-4459-a379-59404b326c7d.png)
The battery %soc displayed at start-up and when the lights button is selected always reads 99.9. There is some fluctuation but it settles on 99.9. The battery voltage reads steady at 41.4V.
Is my set up correct or is there a better way?
Does the soc feature operate corrected or is there a known issue?
Thanks

**Comment by dzid26** [comment]
Assuming you have a "36V battery" (10cells in series), then 41.4V/10 is 4.1V. Thats fully charged. 100% cannot be displayed, so it is showing 99.9.

**Comment by pickerdave** [comment]
Thanks for your reply.
I've used the table to correlatevoltage and soc and it does seem to be correct. 
The soc indication does jump around a little but is certainly good enough.
Thanks

![image](https://user-images.githubusercontent.com/127301018/223803905-16ec51ac-8179-4099-aa17-1c637ad60ec5.png)
