### ISSUE TITLE
Which 860C Display Version I should Install?

### ISSUE THREAD

**Issue by RichardIstSauer** [emmebrusa/TSDZ2-Smart-EBike-1#70]
Hello I installed the newest firmware to the motor v20.1C.2-update-2. But which firmware I should install to the 860c display? Can I take also the newest, v20.1C.4-860C-update-2?

**Comment by emmebrusa** [comment]
This v20.1C.2-update-2 version is only for stock displays,
not good for 860C.
The most recent for 860C is this:
[https://github.com/emmebrusa/TSDZ2-Smart-EBike-860C/releases/tag/v20.1C.4-860C-update-3](url)

**Comment by RichardIstSauer** [comment]
Okay so I can use the latest stable v20.1C.4-860C-update-2? But how I should flash the motor there is no Java Configurator?

**Comment by emmebrusa** [comment]
Update 3 is also stable, we've been testing it since April.
Java configurator should not be used with 860C display.
To flash the motor, use the .hex file and ST Visual Programer with ST-link.
To flash the display, use the .bin file and Apt Burn Tools with bootloader box.

**Comment by RichardIstSauer** [comment]
Is there a guide for flashing the .hex to the motor? And how I can change the settings when using the hex file, like activating the hybrid mode or other things?

**Comment by RichardIstSauer** [comment]
Flashed without any problems
